services:
  django-app:

    image: 479479081438.dkr.ecr.ap-south-1.amazonaws.com/django-app:1.0
    
    container_name: django_app_container

    ports:
      - "8000:8000"
    
    env_file:
      - .env
    
    volumes:
      - sqlite-data:/app/
    
volumes:
  sqlite-data: